apiVersion: v1
kind: ReplicationController
metadata:
  name: updateapp
spec:
  replicas: 3
  selector:
    app: updateapp
  template:
    metadata:
      name: updateapp
      labels:
        app: updateapp
    spec:
      containers:
      - name: updateapp
        image: gcr.io/google_containers/pause:0.8.0
        ports:
        - containerPort: 8080
